### ISSUE TITLE
Poorly documented required beacon's MAC address format

### ISSUE THREAD

**Issue by mzygar** [Estimote/iOS-Indoor-SDK#10]
The location built using `[ESTLocationBuilder addBeaconIdentifiedByMac:....] `is saved only when beacon's MAC addresses are  lowercase, unseparated such as `d49e81631d6a`. Otherwise the API returns vague error `400 : Beacon not found`. This required MAC address format is not documented.

The comments in the examples suggest uppercase: `MAC1`. On the other hand cloud panel suggests colon-separated strings like `d4:9e:81:63:1d:6a`.

I'd suggest either documenting expected MAC address format in method's doc or introduce the formatter which would tranform various input formats to the one expected by your API.

**Comment by heypiotr** [comment]
Yup, thanks for sharing! We've just updated the documentation to state the expected format. The change will go live with the next release.

Accepting multiple formats is also a good idea, we'll add that to a list of our nice-to-haves.
