### ISSUE TITLE
Don't we need to 'NSLocationAlwaysUsageDescription' in Example project

### ISSUE THREAD

**Issue by manjunathgudisi** [Estimote/iOS-Indoor-SDK#11]
Hi, 

Don't we need to add 'NSLocationAlwaysUsageDescription' (or at least 'NSLocationWhenInUseUsageDescription') to info.plist to get the location permissions to monitor and range the beacons on iOS8.

Have a look at the attached images. I have downloaded this project and tried to test the 'Indoor Navigation' app. In Settings, I don't have any location access.

When I wants to configure my beacons, its giving an error 'No beacons were detected'. Its valid because we are trying to monitor the beacons without location access. It should not work as expected. 

Let me know am I correct or not.

------------ -------
I have added 'NSLocationAlwaysUsageDescription' tag to info.plist to try and test the app. No where its asking for location access. ideally, iOS8 will show an alert for location access to allow the user to get the access. Since its not showing alert even after I add 'NSLocationAlwaysUsageDescription' tag. So, Still the settings are same.

Seems, something is missing in the code.
-------------------

Can you please check this issue. Thank you.

![img_0079](https://cloud.githubusercontent.com/assets/6059076/8476426/cf461a3a-20de-11e5-8ac2-0ee7b3f0aa1d.PNG)
![img_0080](https://cloud.githubusercontent.com/assets/6059076/8476428/cf982e9c-20de-11e5-95a8-f87cc7e2b30c.PNG)
![img_0081](https://cloud.githubusercontent.com/assets/6059076/8476427/cf94e2d2-20de-11e5-8643-c2991dfda0ee.PNG)

**Comment by heypiotr** [comment]
Hi, thanks for taking your time to write this up (:

At this point, Indoor Location doesn't rely on Location Services, monitoring and ranging.

The reason why your beacons are not detected is probably a different one. If you log in to [cloud.estimote.com](cloud.estimote.com) with the same account you're using to log in to the example app, can you see your beacons there?

I'll close this issue as there's no apparent bug, but feel free to reply in here for individual troubleshooting.
