### ISSUE TITLE
Can not run 

### ISSUE THREAD

**Issue by Mr-Luxry** [Estimote/iOS-Indoor-SDK#16]
hello friends,
 i am a developer in shanghai china. several days early i have downloaded your demo created by swift.but i can not run it in my iPhone  5s.the error is that 

"dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/mobile/Containers/Bundle/Application/428E6679-7FDC-4589-8DFE-BBE0C723B42C/IndoorMap.app/IndoorMap
  Reason: no suitable image found.  Did find:
    /private/var/mobile/Containers/Bundle/Application/428E6679-7FDC-4589-8DFE-BBE0C723B42C/IndoorMap.app/Frameworks/libswiftCore.dylib: mmap() error 1 at address=0x100524000, size=0x00220000 segment=__TEXT in Segment::map() mapping /private/var/mobile/Containers/Bundle/Application/428E6679-7FDC-4589-8DFE-BBE0C723B42C/IndoorMap.app/Frameworks/libswiftCore.dylib "

<img width="726" alt="2016-07-01 11 57 40" src="https://cloud.githubusercontent.com/assets/13265870/16511481/0df99e32-3f83-11e6-9b05-548427927e08.png">

i have tried many solutions to solve  this problem,but all of them dose not worked.so i come here to look for your help .
lookforward to your reply.
thanks!

**Comment by ashleyxly** [comment]
Hi. I encountered similar error when trying to integrate a third party framework A into an application B. It is solved by navigating to B's targets' General tab, and adding A to "Embedded Binaries" field.
