### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by jkananth** [Estimote/iOS-Indoor-SDK#17]
I followed the steps as it is(manual addition of SDK) in the tutorial bur when I try to build the application it is showing error as its not able to import the EILIndoorSDK.h file. I am using  Xcode version 8.1 with Swift 3 +
![screen shot 2016-12-22 at 7 19 38 pm](https://cloud.githubusercontent.com/assets/24432912/21427646/c8172f42-c87b-11e6-9c9d-1adfe96a2fe5.png)
.
![screen shot 2016-12-22 at 7 06 47 pm](https://cloud.githubusercontent.com/assets/24432912/21427341/0fd7bd08-c87a-11e6-8e7a-5fced1312c86.png)

**Comment by Nicho123** [comment]
Good Day, I have the same issue was this resolved?

**Comment by Mycek** [comment]
@Nicho123 
With latest SDK following the manual installation process the issue does not occur. Could you post the errors you get?

**Comment by CyrussWong** [comment]
Hi ! I am a beginner of swift 3 and estimoteSDK. I have the same issue too.
Here are my error message.

![image](https://cloud.githubusercontent.com/assets/26572650/24147899/517ca42e-0e77-11e7-9679-147fa7b6f88c.png)
and 
![image](https://cloud.githubusercontent.com/assets/26572650/24147937/7d0f1928-0e77-11e7-8d8c-6fea22e11e25.png)

I have followed the instruction and used cocoapods to add the "estimoteIndoorSDK" into the project. I have already add the bridge.h and point it to the "Objective-C Bridging Header". And it still error.

**Comment by heypiotr** [comment]
Did you remember to open the .xcworkspace file, not the .xcodeproj file?

**Comment by CyrussWong** [comment]
Thank you for reply. Of course i did so. 
But now, I am successfully import it.
Because I import the library directly now without using cocoapod.

**Comment by Mycek** [comment]
I'm closing the issue for now. I you encounter similar issues please post them as a new one :)
