### ISSUE TITLE
Import ESTConfig.h  &   Import EILIndoorLocationManager.h   not working

### ISSUE THREAD

**Issue by Nicho123** [Estimote/iOS-Indoor-SDK#18]
Following the tutorial on how to create the Indoor Location App. However receiving the following errors 
![sdkerrors](https://cloud.githubusercontent.com/assets/26366685/23835729/be50a41a-0742-11e7-8cdc-8a4a4ab35329.PNG)

Coding in Objective-C 
Using OSX 10.11 El Capitan
XCode 8.2.1

**Comment by djoeman84** [comment]
Not an iOS engineer and not sure if this is right, but I fixed this issue by importing explicitly:

`#import "Pods/EstimoteSDK/EstimoteSDK/EstimoteSDK.framework/Headers/ESTConfig.h"`
or whatever the path to the install is.
Your setup looks different than mine, so this might not work.

**Comment by Nicho123** [comment]
djoeman84, Thanx alot bro. Did what you said and placed the exact path location, in front of the import and it imports fine.
