### ISSUE TITLE
Estimote Fetch Location Issues in Objective C

### ISSUE THREAD

**Issue by Nicho123** [Estimote/iOS-Indoor-SDK#19]
Below is an issue I recently encountered, at the moment this error is paralyzing my progress to actually test the application
![estimotefetcherrors](https://cloud.githubusercontent.com/assets/26366685/23874799/50a02b54-080d-11e7-9758-359ec608fad3.PNG)

Note: My App ID and Taken were entered, along with my Location Identifier 
Using Xcode 7

**Comment by ivanlyubimov** [comment]
@Nicho123 I'm having same issue, could you clarify how you solved this?

**Comment by timotheeduran** [comment]
Hey, I have the same problem with EILPoint, how did you resolve the problem ?
