### ISSUE TITLE
Using ARKit location together with custom ARSCNView

### ISSUE THREAD

**Issue by kasperekt** [Estimote/iOS-Indoor-SDK#23]
I would like to use experimental ARKit location method, but it seems that it takes camera resource and I can't create custom scene with ARSCNView. Is there a way to use the same session to improve indoor location accuracy and e.g. draw objects etc.?

**Comment by Mycek** [comment]
Hi @kasperekt !
It takes camera resource, but not hides it. In your `ARSCNView` you should just use the `arSession ` provided by the `EILIndoorLocationManager`.

**Comment by kasperekt** [comment]
Yes. That was sufficient. Thank you.

**Comment by elmz87** [comment]
any examples? would appreciate it! how to use the x and y for the arscnview?
