### ISSUE TITLE
Issues with Indoor Location App

### ISSUE THREAD

**Issue by sahilsarosh** [Estimote/iOS-Indoor-SDK#28]
When creating floor map using the Indoor Location App, I went through all the steps and before it generates the floor map, it gives me this error -  "couldnt confirm settings with all beacons". The beacons seem to be setup right and I am able to connect to beacons just fine and make changes to any of the beacon settings.

Note: I am using iOS Indoor Location App and not using the SDK. Can you help how to fix this? See image attachment.

![1523682758665](https://user-images.githubusercontent.com/6493185/38765632-996ca39e-3f7a-11e8-96de-47663378c929.JPEG)

**Comment by tingyumao** [comment]
I got the same issue and have no idea how to deal with it. Could some one give any hint?

**Comment by sahilsarosh** [comment]
Creating a mesh with the beacons worked. Thanks

**Comment by timotheeduran** [comment]
- Same problem with this app
- Impossible to use the "proximity demo app", no beacons is detected
- CURL request says that "device not in a mesh" but Estimate Cloud says it it
- Impossible to remove a beacon form a mesh
- Impossible to create a mesh by selecting beacons on estimate cloud ans click "create mesh", it says that the firmware must be the same on all devices but it actually is
- Overriding a mesh with curl has no effect but it shows a success
- Removing a beacon with CURL shows success but it is still on the cloud
- Documentation often outdated, we have to guess how to do things

Everything seems to be extremely not reliable, I've spend 2 days just trying to make a simple demo work. Am I the only one ?
