### ISSUE TITLE
Sticker beacon locations are incorrect in Indoor App

### ISSUE THREAD

**Issue by vtavirtualtransit** [Estimote/iOS-Indoor-SDK#29]
From this article, we understand the location of sticker beacon is updated every 3 minutes. https://blog.estimote.com/post/165720366660/estimote-introducing-low-power-asset-tracking-api

However, Indoor App is not showing the correct locations of the sticker beacons even after 3 minutes. Can you please help? We want Indoor App to show proper location (I am using the native App and not any SDK).

**Comment by sahilsarosh** [comment]
Please close this issue. I re-created with a different account. Use the issue below.

https://github.com/Estimote/iOS-Indoor-SDK/issues/30
