### ISSUE TITLE
AppStore App Rejected due ARKit used in the framework but not used

### ISSUE THREAD

**Issue by yo113** [Estimote/iOS-Indoor-SDK#34]
I have integrated Estimote indoor location sdk and one of the framework used in the estimote sdk's file named "EILIndoorLocationManager.h" contains ARSession which is the reason my app got rejected saying the reason 'Apps using ARKit should provide rich and integrated augmented reality experiences. We encourage you to review your app concept and incorporate more robust AR features and functionality. Note that merely dropping a model into an AR view or replaying animation is not enough.'

Is there any update coming for this kind of issue.
Please suggest something for this issue

**Comment by heypiotr** [comment]
Two ideas:

- explain the situation to the App Store reviewers: your app uses an external framework (ours) for indoor positioning, and that framework has optional support for ARKit if someone wants to do indoor positioning in augmented reality—but you're not using that, so the "apps using ARKit" clause shouldn't apply to you

- downgrade to Indoor Location SDK 2.7.1, which doesn't include the AR mode; I believe the API changes between 2.7.1 and 3.0.0 are minimal

**Comment by yo113** [comment]
Thanks Heypioter, just Downgrading the indoor sdk to 2.7.1 and dependant Estimote sdk to 4.25.3.
Will check if it works or pass the appstore review process

**Comment by heypiotr** [comment]
Fingers crossed, and congrats on your app! Feel free to share a link once it hits the App Store (;
