### ISSUE TITLE
Not working out of the box with Cocoapods 0.36.4 and use_frameworks

### ISSUE THREAD

**Issue by alanhartless** [Estimote/iOS-Indoor-SDK#7]
I have to use a project that's mixed with Swift (such as Alamofire) and Objective C libraries (such as this). But Xcode can't find EstimoteIndoorSDK files after installing with Cocoapods 0.36.4 with use_frameworks.  Supposedly we don't need the bridging header files now with the use_frameworks setting. I did end up getting it to work but had to do some finagling to do so.  I had to use `import EstimoteIndoorSDK` at the tops of my ViewControllers and then had to change 

```
#import "ESTBeacon.h"
#import "ESTDefinitions.h"
```

in ESTPositionedBeacon.h (https://github.com/Estimote/iOS-Indoor-SDK/blob/master/EstimoteIndoorLocationSDK/Headers/ESTPositionedBeacon.h#L4-L5) to 

```
#import <EstimoteSDK/ESTBeacon.h>
#import <EstimoteSDK/ESTDefinitions.h>
```

That allowed me to at least build and use the example files.

**Comment by dasdany** [comment]
I have the same problem, but don't get fixed. I would like to use EstimoteSDK, but Xcode can't find it.
My Podfile:
    
    platform :ios, '8.4'
    # Look for target to link with in an Xcode project called
    # `beaconTest.xcodeproj`.
    xcodeproj 'beaconTest'
    
    # use only frameworks - actual beacuse prgramming in swift
    use_frameworks!
    
    # use this pods
    pod 'EstimoteSDK', '2.4.0'
    pod 'XCGLogger', '~> 2.1'
    
    link_with 'beaconTest', 'beaconTestTests'
    
    # for specific things
    target 'beaconTest' do
    
    end
    
    target 'beaconTestTests' do
    
    end

My first try was to use a bridging-header. That doesn't work. My second try was to import it like alanhartless (or like http://www.innerexception.com/2015/05/cocoapods-useframeworks-means-bridging.html). XCGLogger can be used, but not EstimoteSDK. Any ideas?

My System:
Xcode 6
Cocoa Pods 0.37.2

**Comment by FranciscoG** [comment]
+1
not working for me either

Xcode 7.2.1
Cocoapods 1.0.0

**Comment by Mycek** [comment]
This issue should be fixed in the newest Indoor Location SDK. If you encounter similar problems please re-open or post a new issue! :)

**Comment by mdramos** [comment]
Im seeing this issue with the latest

**Comment by Mycek** [comment]
@mdramos Could you describe the steps to reproduce the behaviour you are experiencing?
Did it occur on second attempt as well?
