### ISSUE TITLE
Can't create correct location using ESTLocationBuilder

### ISSUE THREAD

**Issue by sashakid** [Estimote/iOS-Indoor-SDK#9]
Hi, guys, I can't create correct location manually and have some questions about it. I draw picture to explain what location I want to build. I was looking for answers on my question in your manual and in comments for SDK code but I still can't understand some moments:
1. What is ESTLocationBuilderSide? How can I implement correctly these values for my location?
2. How to implement setLocationOrientation:? Is it value in degrees of my deflection from North when I stay face to my location top? (see my picture)

![screenshot 2015-05-21 12 11 52](https://cloud.githubusercontent.com/assets/5786373/7745282/a6df76ba-ffb2-11e4-8917-95cf8cff3d05.png)

```objc
    ESTLocationBuilder *locationBuilder = [ESTLocationBuilder new];
    [locationBuilder setLocationBoundaryPoints:@[
                                                 [ESTPoint pointWithX:0 y:0],
                                                 [ESTPoint pointWithX:0 y:7.46],
                                                 [ESTPoint pointWithX:7.6 y:7.46],
                                                 [ESTPoint pointWithX:7.6 y:0]
                                                 ]];
    
    [locationBuilder setLocationOrientation:275];
    
    [locationBuilder addBeaconIdentifiedByMac:kBeaconMac1
                       atBoundarySegmentIndex:0
                                   inDistance:0
                                     fromSide:ESTLocationBuilderLeftSide];
    
    [locationBuilder addBeaconIdentifiedByMac:kBeaconMac2
                       atBoundarySegmentIndex:1
                                   inDistance:0
                                     fromSide:ESTLocationBuilderLeftSide];
    
    [locationBuilder addBeaconIdentifiedByMac:kBeaconMac3
                       atBoundarySegmentIndex:2
                                   inDistance:0
                                     fromSide:ESTLocationBuilderRightSide];
    
    [locationBuilder addBeaconIdentifiedByMac:kBeaconMac4
                       atBoundarySegmentIndex:3
                                   inDistance:0
                                     fromSide:ESTLocationBuilderRightSide];
    
    self.location = [locationBuilder build];
```

This is my code, please, tell me what am I doing wrong. Thanks :-)

**Comment by mzygar** [comment]
>1. What is ESTLocationBuilderSide? How can I implement correctly these values for my location?

In ESTLocationBuilder.h there's a comment saying it's: `/** Side of the boundary segment as seen from inside of the location. */`

I'm not sure about 2. but I think you get it right. Let's wait for Estimote's answer.

There is one more thing I see in your code:
```
[locationBuilder addBeaconIdentifiedByMac:kBeaconMac1
                       atBoundarySegmentIndex:0
                                   inDistance:0
                                     fromSide:ESTLocationBuilderLeftSide];
```

In your case, Beacon1 is in the middle of the wall, so the value of paramter `inDistance` should equal 7.46/2= `3.73 `meteres from whichever side (left or right), as it is centered ;)

**Comment by sashakid** [comment]
@mzygar How can I understand it? I've read all comments) My walls are boundary segments, I have 4 walls and location's shape is rectangular. Which of my boundary segments are on left side and which on right side? Or should I use nil for top and bottom (the wall in front of me and the wall besides me) and ESTLocationBuilderLeftSide for only left side and ESTLocationBuilderRightSide for right? Thanks.

**Comment by mzygar** [comment]
Imagine you are standing in the middle of the room. 

You take a look at the first wall (boundarySegmentIndex:0), the one with Beacon1 on it. You measure the distance between the beacon and right or left end of the wall. You put the result in `[locationBuilder addBeaconIdentifiedByMac:MAC1 atBoundarySegmentIndex:0
                                   inDistance:<YOUR DISTANCE HERE>
                                     fromSide:<LEFT OR RIGHT HERE>;]` repectively. 
Then you repeat the process for the remaining walls(changing boundarySegementIndex accordingly)

Does that make sense?

**Comment by sashakid** [comment]
Ok, I understand what you mean.
> distance between the beacon and right or left end of the wall
In my case for 1st wall it will be:
```objc
[locationBuilder addBeaconIdentifiedByMac:kBeaconMac1
                       atBoundarySegmentIndex:0
                                   inDistance:3.73
                                     fromSide:ESTLocationBuilderLeftSide];
```
So, I shouldn't repeat the same for right side?

**Comment by mzygar** [comment]
Nope, you measure once per beacon. If you measured the distance to the left side, there is no need to measure distance to the right(as the SDK can compute it). You just move on to the next beacon/wall.

**Comment by sashakid** [comment]
@mzygar thanks for explaining :-) Maybe someone could help me with 2nd question.

**Comment by heypiotr** [comment]
For the 2nd question: align yourself along the [0,1] vector. Looking at your floor plan, that'd be "facing the top". Then open the compass app, read the number it shows, punch it into the `setLocationOrientation:` method. Let us know if this solves your problem (:

Really appreciate you coming here with your issue, it tells us know our documentation still needs some work. Thank you! :bowtie: :tada:

BTW, in the future, consider posting on our forums instead: [forums.estimote.com](https://forums.estimote.com) :wink:

**Comment by sashakid** [comment]
Thanks, it works )
